#!/usr/bin/env python
#
# Mock firewalld-cmd executable for running inside containers

import argparse
parser = argparse.ArgumentParser("Mock firewalld-cmd for testing")
parser.add_argument("--state", action="store_true")
parser.add_argument("--permanent", action="store_true")
parser.add_argument("--get-zones", action="store_true")
parser.add_argument("--reload", action="store_true")
parser.add_argument("--get-target", action="store_true")
parser.add_argument("--list-rich-rules", action="store_true")
parser.add_argument("--list-services", action="store_true")
parser.add_argument("--list-ports", action="store_true")
parser.add_argument("--zone")
parser.add_argument("--remove-service")
parser.add_argument("--add-service")

args = parser.parse_args()

if args.state:
    print("running")
elif args.permanent and args.get_zones:
    print("block dmz drop external home internal public trusted work")
elif args.permanent and args.zone and args.get_target:
    print("default")
elif args.permanent and args.zone and args.list_rich_rules:
    print("")
elif args.permanent and args.zone and args.list_services:
    print("ssh nrpe")
elif args.permanent and args.zone and args.list_ports:
    print("")
elif args.permanent and args.zone and args.remove_service:
    print("removed " + args.remove_service)
elif args.reload:
    print("firwalld was reloaded...")
