#!/usr/bin/env python
#
# Mock getsebool executable for running inside containers

import argparse
import sys

parser = argparse.ArgumentParser("Mock getsebool for testing")
parser.add_argument('key', nargs='?')

args = parser.parse_args()

if args.key:
  # read the key from /tmp/sebool/KEY, defaulting to 0
  try:
    value = open('/tmp/sebool/%s' % (args.key), 'r').read()
  except IOError:
    value = "off"

  print "haproxy_connect_any --> %s" % (value)
else:
  print "missing key"
  sys.exit(1)
