#!/usr/bin/env python
#
# Mock getsebool executable for running inside containers

import argparse
import sys
import os

parser = argparse.ArgumentParser("Mock setsebool for testing")
parser.add_argument('key', nargs='?')
parser.add_argument('value', nargs='?')
parser.add_argument('-P', action="store_true")

args = parser.parse_args()

if args.key and args.value:
  # write the key from /tmp/sebool/KEY, defaulting to 0
  if not os.path.isdir("/tmp/sebool"):
    os.mkdir("/tmp/sebool")


  with open('/tmp/sebool/%s' % (args.key), 'w') as f:
    f.write(args.value)

else:
  print "missing key or value"
  sys.exit(1)
