#! /bin/bash
#
# splunk       Mock splunk forwarder
#
# chkconfig: 2345 10 90
# description: mock splunk forwarder service
#
### BEGIN INIT INFO
# Provides: splunk
# Short-Description: mock splunk forwarder service
### END INIT INFO
